config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_for :users, controllers: { registrations: 'registrations' }

  get '/underlyings.json' => 'underlyings#index'

  get '/welcome' => 'ocraft#welcome'

  get 'trade_param_sets/:id', to: 'trade_param_sets#show', as: 'trade_param_set'

  patch 'trade_param_sets/:id' => 'trade_param_sets#update'

  resources :positions

  post 'ghwebapi/batch_update' => 'ghwebapi#batch_update'
  post 'positions/batch_update' => 'positions#batch_update'

  get 'ghwebapi/chains_for_symbol/:symbol/:series' =>
      'ghwebapi#chains_for_symbol', :constraints => { symbol: /[^\/]+/ }

  post 'ghwebapi/fetch_options', to: 'ghwebapi#fetch_options'

  get 'ocraft/index' => 'ocraft#index'

  get '/about' => 'ocraft#about'

  get '/contact' => 'ocraft#contact'

  get '/screener' => 'ocraft#screener'

  post 'ocraft/forwardtest' => 'ocraft#forwardtest'

  get '/user_spreads' => 'ocraft#saved_spreads'

  root 'ocraft#index'
end

app/models/underlying.rb
require 'global_config'

class Underlying < ActiveRecord::Base
  before_destroy { |u| Option.where(underlying_symbol: u.om_symbol).destroy_all }

  def self.create_from_csv_row(row, params)
    under = Underlying.find_by(om_symbol: row[0])
    opt_vol = row[params[:vol_index]].to_i
    if under
      under.update(avg_daily_opt_volume: opt_vol)
      return nil
    else
      Underlying.create(
        tda_symbol: row[0],
        om_symbol: row[0],
        yh_symbol: row[0],
        name: row[1],
        asset_type: params[:asset_type],
        avg_daily_opt_volume: opt_vol
      )
    end
  end
end

app/controllers/underlyings_controller.rb
#
class UnderlyingsController < ApplicationController
  before_action :set_underlying, only: [:show, :edit, :update, :destroy]

  # GET /underlyings
  # GET /underlyings.json
  def index
    # eliminate problematic underlyings. NOT OUR PROBLEM.
    # @underlyings = Underlying.all
    @underlyings = Underlying.where(
      'implied_volatility > 0 AND recent_price IS NOT NULL'
    )
    render json: @underlyings
  end

  # GET /underlyings/1
  # GET /underlyings/1.json
  def show
  end

  # GET /underlyings/new
  def new
    @underlying = Underlying.new
  end

  # GET /underlyings/1/edit
  def edit
  end

  # POST /underlyings
  # POST /underlyings.json
  def create
    @underlying = Underlying.new(underlying_params)

    respond_to do |format|
      if @underlying.save
        format.html do
          endredirect_to @underlying, notice: 'Underlying was successfully created.'
        end
        format.json { render :show, status: :created, location: @underlying }
      else
        format.html { render :new }
        format.json { render json: @underlying.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /underlyings/1
  # PATCH/PUT /underlyings/1.json
  def update
    respond_to do |format|
      if @underlying.update(underlying_params)
        format.html do
          endredirect_to @underlying, notice: 'Underlying was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @underlying }
      else
        format.html { render :edit }
        format.json { render json: @underlying.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /underlyings/1
  # DELETE /underlyings/1.json
  def destroy
    @underlying.destroy
    respond_to do |format|
      format.html do
        endredirect_to underlyings_url, notice: 'Underlying was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions
  def set_underlying
    @underlying = Underlying.find(params[:id])
  end

  # Never trust parameters from the internet, only allow the white list through.
  def underlying_params
    params.require(:underlying).permit(
      :tda_symbol, :om_symbol,
      :yh_symbol, :name, :asset_type,
      :last_earnings_date, :next_earnings_date,
      :last_dividend_date, :avg_daily_opt_volume,
      :historic_volatility, :implied_volatility,
      :iv_rank, :trend,
      :rsi, :recent_price
    )
  end
end

app/helpers/underlyings_helper.rb
module UnderlyingsHelper
end

app/views/underlyings/_form.html.erb
<%= form_for(@underlying) do |f| %>
  <% if @underlying.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@underlying.errors.count, "error") %> prohibited this underlying from being saved:</h2>

      <ul>
      <% @underlying.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tda_symbol %><br>
    <%= f.text_field :tda_symbol %>
  </div>
  <div class="field">
    <%= f.label :om_symbol %><br>
    <%= f.text_field :om_symbol %>
  </div>
  <div class="field">
    <%= f.label :yh_symbol %><br>
    <%= f.text_field :yh_symbol %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :asset_type %><br>
    <%= f.text_field :asset_type %>
  </div>
  <div class="field">
    <%= f.label :last_earnings_date %><br>
    <%= f.text_field :last_earnings_date %>
  </div>
  <div class="field">
    <%= f.label :next_earnings_date %><br>
    <%= f.text_field :next_earnings_date %>
  </div>
  <div class="field">
    <%= f.label :last_dividend_date %><br>
    <%= f.text_field :last_dividend_date %>
  </div>
  <div class="field">
    <%= f.label :avg_daily_opt_volume %><br>
    <%= f.number_field :avg_daily_opt_volume %>
  </div>
  <div class="field">
    <%= f.label :historic_volatility %><br>
    <%= f.text_field :historic_volatility %>
  </div>
  <div class="field">
    <%= f.label :implied_volatility %><br>
    <%= f.text_field :implied_volatility %>
  </div>
  <div class="field">
    <%= f.label :iv_rank %><br>
    <%= f.text_field :iv_rank %>
  </div>
  <div class="field">
    <%= f.label :trend %><br>
    <%= f.text_field :trend %>
  </div>
  <div class="field">
    <%= f.label :rsi %><br>
    <%= f.text_field :rsi %>
  </div>
  <div class="field">
    <%= f.label :recent_price %><br>
    <%= f.text_field :recent_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/underlyings/edit.html.erb
<h1>Editing Underlying</h1>

<%= render 'form' %>

<%= link_to 'Show', @underlying %> |
<%= link_to 'Back', underlyings_path %>

app/views/underlyings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Underlyings</h1>

<table>
  <thead>
    <tr>
      <th>Tda symbol</th>
      <th>Om symbol</th>
      <th>Yh symbol</th>
      <th>Name</th>
      <th>Asset type</th>
      <th>Last earnings date</th>
      <th>Next earnings date</th>
      <th>Last dividend date</th>
      <th>Options volume</th>
      <th>Historic volatility</th>
      <th>Implied volatility</th>
      <th>Iv rank</th>
      <th>Trend</th>
      <th>Rsi</th>
      <th>Recent Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @underlyings.each do |underlying| %>
      <tr>
        <td><%= underlying.tda_symbol %></td>
        <td><%= underlying.om_symbol %></td>
        <td><%= underlying.yh_symbol %></td>
        <td><%= underlying.name %></td>
        <td><%= underlying.asset_type %></td>
        <td><%= underlying.last_earnings_date %></td>
        <td><%= underlying.next_earnings_date %></td>
        <td><%= underlying.last_dividend_date %></td>
        <td><%= underlying.avg_daily_opt_volume %></td>
        <td><%= underlying.historic_volatility %></td>
        <td><%= underlying.implied_volatility %></td>
        <td><%= underlying.iv_rank %></td>
        <td><%= underlying.trend %></td>
        <td><%= underlying.rsi %></td>
        <td><%= underlying.recent_price %></td>
        <td><%= link_to 'Show', underlying %></td>
        <td><%= link_to 'Edit', edit_underlying_path(underlying) %></td>
        <td><%= link_to 'Destroy', underlying, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Underlying', new_underlying_path %>

app/views/underlyings/new.html.erb
<h1>New Underlying</h1>

<%= render 'form' %>

<%= link_to 'Back', underlyings_path %>

app/views/underlyings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tda symbol:</strong>
  <%= @underlying.tda_symbol %>
</p>

<p>
  <strong>Om symbol:</strong>
  <%= @underlying.om_symbol %>
</p>

<p>
  <strong>Yh symbol:</strong>
  <%= @underlying.yh_symbol %>
</p>

<p>
  <strong>Name:</strong>
  <%= @underlying.name %>
</p>

<p>
  <strong>Asset type:</strong>
  <%= @underlying.asset_type %>
</p>

<p>
  <strong>Last earnings date:</strong>
  <%= @underlying.last_earnings_date %>
</p>

<p>
  <strong>Next earnings date:</strong>
  <%= @underlying.next_earnings_date %>
</p>

<p>
  <strong>Last dividend date:</strong>
  <%= @underlying.last_dividend_date %>
</p>

<p>
  <strong>Options volume:</strong>
  <%= @underlying.avg_daily_opt_volume %>
</p>

<p>
  <strong>Historic volatility:</strong>
  <%= @underlying.historic_volatility %>
</p>

<p>
  <strong>Implied volatility:</strong>
  <%= @underlying.implied_volatility %>
</p>

<p>
  <strong>Iv rank:</strong>
  <%= @underlying.iv_rank %>
</p>

<p>
  <strong>Trend:</strong>
  <%= @underlying.trend %>
</p>

<p>
  <strong>Rsi:</strong>
  <%= @underlying.rsi %>
</p>

<p>
  <strong>Recent Price:</strong>
  <%= @underlying.recent_price %>
</p>

<%= link_to 'Edit', edit_underlying_path(@underlying) %> |
<%= link_to 'Back', underlyings_path %>