config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_for :users, controllers: { registrations: 'registrations' }

  get '/underlyings.json' => 'underlyings#index'

  get '/welcome' => 'ocraft#welcome'

  get 'trade_param_sets/:id', to: 'trade_param_sets#show', as: 'trade_param_set'

  patch 'trade_param_sets/:id' => 'trade_param_sets#update'

  resources :positions

  post 'ghwebapi/batch_update' => 'ghwebapi#batch_update'
  post 'positions/batch_update' => 'positions#batch_update'

  get 'ghwebapi/chains_for_symbol/:symbol/:series' =>
      'ghwebapi#chains_for_symbol', :constraints => { symbol: /[^\/]+/ }

  post 'ghwebapi/fetch_options', to: 'ghwebapi#fetch_options'

  get 'ocraft/index' => 'ocraft#index'

  get '/about' => 'ocraft#about'

  get '/contact' => 'ocraft#contact'

  get '/screener' => 'ocraft#screener'

  post 'ocraft/forwardtest' => 'ocraft#forwardtest'

  get '/user_spreads' => 'ocraft#saved_spreads'

  root 'ocraft#index'
end

app/models/trade_param_set.rb
class TradeParamSet < ActiveRecord::Base
  belongs_to :user
  def self.default_set
    TradeParamSet.new(
      name: 'MySet',
      near_strike_max_delta: 0.15,
      min_open_interest: 200,
      min_mark_premium: 0.15,
      max_margin_per_trade: 1000,
      min_percent_rom: 0.01,
      avoid_earnings: true,
      total_margin: 5000,
      commission_base: 4.95,
      commission_per_contract: 0.50,
      commission_min: 0.0,
      recommended_flag: true,
      ds_near_strike_min_delta: 0.35
      # avoid_dividends: nil,
      # min_options_volume: nil,
    )
  end
end

app/controllers/trade_param_sets_controller.rb
#
# Important class documentation
#
class TradeParamSetsController < ApplicationController
  before_action :set_trade_param_set, only: [:show, :edit, :update, :destroy]

  # GET /trade_param_sets
  # GET /trade_param_sets.json
  def index
    @trade_param_sets = TradeParamSet.all
  end

  # GET /trade_param_sets/1
  # GET /trade_param_sets/1.json
  def show
  end

  # GET /trade_param_sets/new
  def new
    @trade_param_set = TradeParamSet.new
  end

  # GET /trade_param_sets/1/edit
  def edit
  end

  # POST /trade_param_sets
  # POST /trade_param_sets.json
  def create
    @trade_param_set = TradeParamSet.new(trade_param_set_params)
    respond_to do |format|
      if @trade_param_set.save
        format.html do
          redirect_to @trade_param_set,
                      notice: 'Trade param set was successfully created.'
        end
        format.json do
          render :show, status: :created, location: @trade_param_set
        end
      else
        format.html { render :new }
        format.json do
          render json: @trade_param_set.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /trade_param_sets/1
  # PATCH/PUT /trade_param_sets/1.json
  def update
    respond_to do |format|
      if @trade_param_set.update(trade_param_set_params)
        format.html { head :no_content }
      else
        format.html { redirect_to :back }
      end
    end
  end

  # DELETE /trade_param_sets/1
  # DELETE /trade_param_sets/1.json
  def destroy
    @trade_param_set.destroy
    respond_to do |format|
      format.html do
        redirect_to trade_param_sets_url,
                    notice: 'Trade param set was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trade_param_set
    @trade_param_set = TradeParamSet.find(params[:id])
  end

  # Never trust parameters from the internet, only allow white list through.
  def trade_param_set_params
    params.require(:trade_param_set).permit(
      :name, :near_strike_max_delta,
      :min_open_interest, :min_mark_premium,
      :max_margin_per_trade, :min_percent_rom,
      :avoid_earnings, :avoid_dividends,
      :min_options_volume, :total_margin,
      :commission_base, :commission_per_contract,
      :commission_min, :recommended_flag,
      :ds_near_strike_min_delta
    )
  end
end

app/helpers/trade_param_sets_helper.rb
module TradeParamSetsHelper
end

app/views/trade_param_sets/_form.html.erb
<%= form_for(@trade_param_set) do |f| %>
  <% if @trade_param_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade_param_set.errors.count, "error") %> prohibited this trade_param_set from being saved:</h2>

      <ul>
      <% @trade_param_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :near_strike_max_delta %><br>
    <%= f.text_field :near_strike_max_delta %>
  </div>
  <div class="field">
    <%= f.label :min_open_interest %><br>
    <%= f.number_field :min_open_interest %>
  </div>
  <div class="field">
    <%= f.label :min_mark_premium %><br>
    <%= f.text_field :min_mark_premium %>
  </div>
  <div class="field">
    <%= f.label :max_margin_per_trade %><br>
    <%= f.number_field :max_margin_per_trade %>
  </div>
  <div class="field">
    <%= f.label :total_margin %><br>
    <%= f.number_field :total_margin %>
  </div>
  <div class="field">
    <%= f.label :min_percent_rom %><br>
    <%= f.text_field :min_percent_rom %>
  </div>
  <div class="field">
    <%= f.label :avoid_earnings %><br>
    <%= f.check_box :avoid_earnings %>
  </div>
  <div class="field">
    <%= f.label :avoid_dividends %><br>
    <%= f.check_box :avoid_dividends %>
  </div>
  <div class="field">
    <%= f.label :min_options_volume %><br>
    <%= f.number_field :min_options_volume %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trade_param_sets/edit.html.erb
<h1>Editing Trade Param Set</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade_param_set %> |
<%= link_to 'Back', trade_param_sets_path %>

app/views/trade_param_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trade Param Sets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Near strike max delta</th>
      <th>Min open interest</th>
      <th>Min mark premium</th>
      <th>Max margin per trade</th>
      <th>Total margin</th>
      <th>Min percent rom</th>
      <th>Avoid earnings</th>
      <th>Avoid dividends</th>
      <th>Min options volume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trade_param_sets.each do |trade_param_set| %>
      <tr>
        <td><%= trade_param_set.name %></td>
        <td><%= trade_param_set.near_strike_max_delta %></td>
        <td><%= trade_param_set.min_open_interest %></td>
        <td><%= trade_param_set.min_mark_premium %></td>
        <td><%= trade_param_set.max_margin_per_trade %></td>
        <td><%= trade_param_set.total_margin %></td>
        <td><%= trade_param_set.min_percent_rom %></td>
        <td><%= trade_param_set.avoid_earnings %></td>
        <td><%= trade_param_set.avoid_dividends %></td>
        <td><%= trade_param_set.min_options_volume %></td>
        <td><%= link_to 'Show', trade_param_set %></td>
        <td><%= link_to 'Edit', edit_trade_param_set_path(trade_param_set) %></td>
        <td><%= link_to 'Destroy', trade_param_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade param set', new_trade_param_set_path %>

app/views/trade_param_sets/new.html.erb
<h1>New Trade Param Set</h1>

<%= render 'form' %>

<%= link_to 'Back', trade_param_sets_path %>

app/views/trade_param_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trade_param_set.name %>
</p>

<p>
  <strong>Near strike max delta:</strong>
  <%= @trade_param_set.near_strike_max_delta %>
</p>

<p>
  <strong>Min open interest:</strong>
  <%= @trade_param_set.min_open_interest %>
</p>

<p>
  <strong>Min mark premium:</strong>
  <%= @trade_param_set.min_mark_premium %>
</p>

<p>
  <strong>Max margin per trade:</strong>
  <%= @trade_param_set.max_margin_per_trade %>
</p>

<p>
  <strong>Total margin:</strong>
  <%= @trade_param_set.total_margin %>
</p>

<p>
  <strong>Min percent rom:</strong>
  <%= @trade_param_set.min_percent_rom %>
</p>

<p>
  <strong>Avoid earnings:</strong>
  <%= @trade_param_set.avoid_earnings %>
</p>

<p>
  <strong>Avoid dividends:</strong>
  <%= @trade_param_set.avoid_dividends %>
</p>

<p>
  <strong>Min options volume:</strong>
  <%= @trade_param_set.min_options_volume %>
</p>

<%= link_to 'Edit', edit_trade_param_set_path(@trade_param_set) %> |
<%= link_to 'Back', trade_param_sets_path %>