config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_for :users, controllers: { registrations: 'registrations' }

  get '/underlyings.json' => 'underlyings#index'

  get '/welcome' => 'ocraft#welcome'

  get 'trade_param_sets/:id', to: 'trade_param_sets#show', as: 'trade_param_set'

  patch 'trade_param_sets/:id' => 'trade_param_sets#update'

  resources :positions

  post 'ghwebapi/batch_update' => 'ghwebapi#batch_update'
  post 'positions/batch_update' => 'positions#batch_update'

  get 'ghwebapi/chains_for_symbol/:symbol/:series' =>
      'ghwebapi#chains_for_symbol', :constraints => { symbol: /[^\/]+/ }

  post 'ghwebapi/fetch_options', to: 'ghwebapi#fetch_options'

  get 'ocraft/index' => 'ocraft#index'

  get '/about' => 'ocraft#about'

  get '/contact' => 'ocraft#contact'

  get '/screener' => 'ocraft#screener'

  post 'ocraft/forwardtest' => 'ocraft#forwardtest'

  get '/user_spreads' => 'ocraft#saved_spreads'

  root 'ocraft#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body class="ghw-grey-background">
  <div class="container">
        <!-- Static navbar -->
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button"
                      class="navbar-toggle collapsed"
                      data-toggle="collapse"
                      data-target="#navbar"
                      aria-expanded="false"
                      aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href=<%= root_path %>>Options Craft</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'About', about_path%></li>
                <li><%= link_to 'Contact', contact_path%></li>
                <% if user_signed_in? %>
                  <li><%= link_to 'Screener', screener_path%></li>
                <% end %>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                  <li><p class="navbar-text">Signed in as <%= current_user.email %></p></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to 'Sign in', new_user_session_path %></li>
                  <li><%= link_to 'Sign up', new_user_registration_path %></li>
                <% end %>
              </ul>
            </div><!--/.nav-collapse -->
          </div><!--/.container-fluid -->
        </nav>
  </div>
  <%= yield %>
</body>
</html>